import {
    ElButton,
    ElMenu,
    ElMenuItem,
    ElSubmenu,
    ElIcon,
    ElScrollbar,
    ElDropdown,
    ElDropdownItem,
    ElForm,
    ElFormItem,
    ElCard,
    ElDivider,
    ElInput,
    ElTable,
    ElTableColumn,
    ElSwitch,
    ElDialog,
    ElPagination,
    ElBreadcrumb,
    ElBreadcrumbItem,
} from 'element-plus';

export const components = [
    ElButton,
    ElMenu,
    ElMenuItem,
    ElSubmenu,
    ElIcon,
    ElScrollbar,
    ElDropdown,
    ElDropdownItem,
    ElForm,
    ElFormItem,
    ElCard,
    ElDivider,
    ElInput,
    ElTable,
    ElTableColumn,
    ElSwitch,
    ElDialog,
    ElPagination,
    ElBreadcrumb,
    ElBreadcrumbItem,
]
